# -*- coding: utf-8 -*-
"""audio_piper_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157VE9StmY5dFCa_zaQHD_xgNbx30WDZO
"""

# Install dependencies
!pip install numpy
!pip install piper-tts
!pip install soundfile scipy
!apt-get install -y libsndfile1

import numpy
import soundfile
import scipy
import piper
import torch

from huggingface_hub import snapshot_download
import os

voice_dir = "piper_voices"
if not os.path.exists(voice_dir):
    print("Downloading Piper voices...")
    snapshot_download(repo_id="rhasspy/piper-voices", local_dir=voice_dir, allow_patterns=["en/en_US/amy/medium/*", "en/en_US/joe/medium/*"])
    print("Download complete!")
else:
    print("Voices already downloaded.")

from piper import PiperVoice
import os

# Set device (Piper is CPU-based but GPU can accelerate preprocessing)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Load female voice (Amy)
voice_path = "piper_voices/en/en_US/amy/medium/en_US-amy-medium.onnx"
try:
    voice = PiperVoice.load(voice_path)
    print("Female voice (Amy) loaded successfully!")
except Exception as e:
    print(f"Error loading voice: {e}")

import wave
# Generate speech with joyful tone
text = "Shine bright with GlowVibe Cosmetics! Our new Rainbow Glow Palette brings vibrant colors and long-lasting sparkle to your makeup game! Feel fabulous, look flawless!"
output_path = "output/piper_female_output.wav"
os.makedirs("output", exist_ok=True)

# Open WAV file and synthesize
with wave.open(output_path, "wb") as wav_file:
    voice.synthesize(text, wav_file=wav_file)

# Play audio
from IPython.display import Audio
Audio(output_path)

# Load male voice (Joe)
voice_path = "piper_voices/en/en_US/joe/medium/en_US-joe-medium.onnx"
try:
    voice = PiperVoice.load(voice_path)
    print("Male voice (Joe) loaded successfully!")
except Exception as e:
    print(f"Error loading voice: {e}")

# Generate speech
text = "Get ready to revolutionize your world with the new Quantum X Smartphone! Lightning-fast, stunning visuals, and AI that feels like magic! Unlock your future today!"
output_path = "output/piper_male_output.wav"
with wave.open(output_path, "wb") as wav_file:
    voice.synthesize(text, wav_file=wav_file)

# Play audio
Audio(output_path)